<?php

return [
  /*
  |--------------------------------------------------------------------------
  | WAF Base URL
  |--------------------------------------------------------------------------
  |
  | The base URL used for generating WAF proxy URLs. This should be the
  | public-facing URL where the WAF service is accessible.
  |
  */
  'base_url' => env('WAF_BASE_URL', env('APP_URL', 'http://localhost')),

  /*
  |--------------------------------------------------------------------------
  | WAF URL Path Prefix
  |--------------------------------------------------------------------------
  |
  | The URL path prefix for WAF proxy endpoints. The Flask WAF uses
  | /waf-flask/{token}/ as the public URL format.
  |
  */
  'url_prefix' => env('WAF_URL_PREFIX', '/waf-flask'),

  /*
  |--------------------------------------------------------------------------
  | WAF Token Map File Path
  |--------------------------------------------------------------------------
  |
  | The path to the JSON map file that contains token -> origin mappings.
  | This file is auto-generated by the backend when proxies are created,
  | updated, or deleted. The Flask WAF reads this file to resolve tokens.
  |
  */
  'map_file_path' => env('WAF_MAP_FILE_PATH', '/shared/waf-map.json'),

  /*
  |--------------------------------------------------------------------------
  | Flask WAF Log File Path
  |--------------------------------------------------------------------------
  |
  | Path to the Flask WAF suspicious activity log file. This JSON-lines
  | file contains all detected/blocked requests with attack information.
  |
  */
  'flask_log_file' => env('WAF_LOG_FILE', '/var/log/waf/suspicious.log'),

  /*
  |--------------------------------------------------------------------------
  | Log Retention
  |--------------------------------------------------------------------------
  |
  | Number of days to retain parsed log entries in the database.
  |
  */
  'log_retention_days' => env('WAF_LOG_RETENTION_DAYS', 30),

  /*
  |--------------------------------------------------------------------------
  | Counter Update Interval
  |--------------------------------------------------------------------------
  |
  | How often (in seconds) the background job should update counters
  | from the log files.
  |
  */
  'counter_update_interval' => env('WAF_COUNTER_UPDATE_INTERVAL', 60),
];
