<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * SIEM Alert Model
 * 
 * Represents security alerts generated by the SIEM tool.
 * Stores alerts locally for persistence, querying, and reporting.
 *
 * @property int $id
 * @property string|null $siem_alert_id
 * @property string|null $rule_id
 * @property string $rule_name
 * @property string $severity
 * @property string|null $description
 * @property string $log_entry
 * @property string $source
 * @property string|null $tip_label
 * @property float|null $tip_confidence
 * @property bool|null $tip_is_malicious
 * @property bool $acknowledged
 * @property \Carbon\Carbon|null $alert_timestamp
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class SiemAlert extends Model
{
  use HasFactory;

  /**
   * The table associated with the model.
   */
  protected $table = 'siem_alerts';

  /**
   * The attributes that are mass assignable.
   */
  protected $fillable = [
    'siem_alert_id',
    'rule_id',
    'rule_name',
    'severity',
    'description',
    'log_entry',
    'source',
    'tip_label',
    'tip_confidence',
    'tip_is_malicious',
    'acknowledged',
    'alert_timestamp',
  ];

  /**
   * The attributes that should be cast.
   */
  protected $casts = [
    'tip_confidence' => 'float',
    'tip_is_malicious' => 'boolean',
    'acknowledged' => 'boolean',
    'alert_timestamp' => 'datetime',
  ];

  /**
   * Severity levels in order of priority.
   */
  public const SEVERITY_LOW = 'LOW';
  public const SEVERITY_MEDIUM = 'MEDIUM';
  public const SEVERITY_HIGH = 'HIGH';
  public const SEVERITY_CRITICAL = 'CRITICAL';

  /**
   * Get all severity levels.
   */
  public static function severities(): array
  {
    return [
      self::SEVERITY_LOW,
      self::SEVERITY_MEDIUM,
      self::SEVERITY_HIGH,
      self::SEVERITY_CRITICAL,
    ];
  }

  /**
   * Scope a query to only include unacknowledged alerts.
   */
  public function scopeUnacknowledged($query)
  {
    return $query->where('acknowledged', false);
  }

  /**
   * Scope a query to only include acknowledged alerts.
   */
  public function scopeAcknowledged($query)
  {
    return $query->where('acknowledged', true);
  }

  /**
   * Scope a query to filter by severity.
   */
  public function scopeBySeverity($query, string $severity)
  {
    return $query->where('severity', strtoupper($severity));
  }

  /**
   * Scope a query to filter by source.
   */
  public function scopeBySource($query, string $source)
  {
    return $query->where('source', $source);
  }

  /**
   * Scope a query to filter by date range.
   */
  public function scopeBetweenDates($query, $from, $to)
  {
    return $query->whereBetween('alert_timestamp', [$from, $to]);
  }

  /**
   * Scope a query to get recent alerts.
   */
  public function scopeRecent($query, int $hours = 24)
  {
    return $query->where('alert_timestamp', '>=', now()->subHours($hours));
  }

  /**
   * Scope a query to get critical and high severity alerts.
   */
  public function scopeCriticalAndHigh($query)
  {
    return $query->whereIn('severity', [self::SEVERITY_CRITICAL, self::SEVERITY_HIGH]);
  }

  /**
   * Check if the alert is critical.
   */
  public function isCritical(): bool
  {
    return $this->severity === self::SEVERITY_CRITICAL;
  }

  /**
   * Check if the alert is high severity.
   */
  public function isHighSeverity(): bool
  {
    return $this->severity === self::SEVERITY_HIGH;
  }

  /**
   * Check if the alert has TIP analysis results.
   */
  public function hasTipAnalysis(): bool
  {
    return $this->tip_label !== null;
  }

  /**
   * Check if TIP flagged this as malicious.
   */
  public function isTipMalicious(): bool
  {
    return $this->tip_is_malicious === true;
  }

  /**
   * Acknowledge the alert.
   */
  public function acknowledge(): bool
  {
    return $this->update(['acknowledged' => true]);
  }

  /**
   * Get a human-readable severity label with color.
   */
  public function getSeverityLabelAttribute(): array
  {
    return match ($this->severity) {
      self::SEVERITY_CRITICAL => ['label' => 'Critical', 'color' => '#dc2626'],
      self::SEVERITY_HIGH => ['label' => 'High', 'color' => '#ea580c'],
      self::SEVERITY_MEDIUM => ['label' => 'Medium', 'color' => '#ca8a04'],
      self::SEVERITY_LOW => ['label' => 'Low', 'color' => '#16a34a'],
      default => ['label' => 'Unknown', 'color' => '#6b7280'],
    };
  }

  /**
   * Get a truncated log entry for display.
   */
  public function getTruncatedLogAttribute(): string
  {
    if (strlen($this->log_entry) <= 200) {
      return $this->log_entry;
    }
    return substr($this->log_entry, 0, 200) . '...';
  }

  /**
   * Convert to array with additional computed attributes.
   */
  public function toArray(): array
  {
    $array = parent::toArray();
    $array['severity_label'] = $this->severity_label;
    $array['truncated_log'] = $this->truncated_log;
    $array['has_tip_analysis'] = $this->hasTipAnalysis();
    return $array;
  }
}
